### ISSUE TITLE
testnet node can not sync

### ISSUE THREAD

**Issue by neal-zhu** [Qitmeer/qitmeer#579]
branch: 0.10.3-rel
node can not sync for 3 days, log stopped flushing after this
`
2021-08-18|06:57:03.003 [INFO ] 16Uiu2HAmTdcrQ2S4MD6UxeR81Su8DQdt2eB7vLzJA7LrawNf93T2 direction:Outbound multiAddr:/ip4/203.86.236.19/tcp/28130/p2p/16Uiu2HAmTdcrQ2S4MD6UxeR81Su8DQdt2eB7vLzJA7LrawNf93T2  (Relay) module=SYNC
`
for a long time

**Comment by dindinw** [comment]
1.  you need a public ip for your node to work properly. 
2.  make sure you open the firewall to allow access to your port (`18150` by default for the 0.10 testnet)
you can test if it works to execute the following `telnet` command from your client PC.
```
telnet <your_public_ip> 18150 (or your customized port number)
```
3.  BTW, `-d` option can be used to change the logging level (ex. `-d trace`) so that node can provide more information. see ```qitmeer --help ``` for more details.

**Comment by dindinw** [comment]
@neal-zhu The issue is closed since no further information provided for a long time.  Please re-open it if you still got sync issue. you might want to try the latest version of the qitmeer, if the old version not works for you.
