### ISSUE TITLE
孤块率太高

### ISSUE THREAD

**Issue by neal-zhu** [Qitmeer/qitmeer#669]
你好，
我们开发的 pool 发现孤块率异常的高，达到了 80%+。根本无法正常使用。
孤块主要原因是节点更新块的速度太慢，有高达几十秒的延迟。请问该如何解决？

**Comment by dindinw** [comment]
@neal-zhu 

Please provide more information to investigate 
 - your qitmeer version ( the output of the `qitmeer --version` command)
 - you network (mainnet or testnet): 
 - your nodeinfo:
    - see https://qitmeer.github.io/docs/en/json-rpc-api/getnodeinfo/ for details
 - your peerinfo, for the most cases, the slow block sync caused by the slow connections, please make sure your peers's `morder` and `mheight` is always on the latest status. 
    - see https://qitmeer.github.io/docs/en/json-rpc-api/getpeerinfo/ for details 

Anyway, You must make sure your node work properly and catch up the latest blockdag status before your pool working properly.
